### ISSUE TITLE
Can't use Twig variable in "fromAddress"

### ISSUE THREAD

**Issue by lucianobargmann** [lexik/LexikMailerBundle#31]
Hi there,

From your documentation, it seems I cannot use a twig var like {{ senderAddress }} in fromAddress field.

I have several deployments of my app, each one has a different sender address and name.

Since I could not find any examples in your code, tests or documentation, I wonder if this is n issue or I just need some guidance.

Thanks for your work,
Luciano

**Comment by Rvanlaak** [comment]
The `from_address` also should support i18n for each mailing right? We want to start using the Bundle as the basis of our built-in customer support system.

**Comment by cedric-g** [comment]
On branch `master` the `from_address` field is now a twig template (see PR https://github.com/lexik/LexikMailerBundle/pull/37).

What do mean by support i18n ? the `from_address` is in the `EmailTranslation` that contains fields for one locale.

**Comment by Rvanlaak** [comment]
> the from_address is in the EmailTranslation that contains fields for one locale.
That is exactly what I mean. We would like to send our German emails from the .de domain.
