### ISSUE TITLE
About sonata admin config

### ISSUE THREAD

**Issue by mlelong** [lexik/LexikMailerBundle#45]
Hello,

We are using now your mailer bundle and i was wondering why you don't hide the translation admins on sonata dashboard. Is there a particular reason ?

This can be done using show_in_dashboard option like this : 

        <service id="lexik_mailer.admin.layout_translation" class="%lexik_mailer.admin.layout_translation.class%">
            <tag name="sonata.admin" manager_type="orm" group="Autre" show_in_dashboard="false" label="Layouts Translations" label_translator_strategy="sonata.admin.label.strategy.underscore" />

Thanks for your work,
Mickael

**Comment by slashfan** [comment]
Hi,

As we don't usually use the default sonata dashboard we didn't see it. 

Please feel free to make a PR if it's a problem for you or if you see any improvement that can be made to the sonata integration (which is quite recent and is very basic at the moment).

**Comment by mlelong** [comment]
Work well :+1:
