### ISSUE TITLE
Adding Attachments

### ISSUE THREAD

**Issue by liamsorsby** [lexik/LexikMailerBundle#65]
Will there be any support for adding attachments in any upcoming releases as it's not stated in the documentation.

**Comment by spike31** [comment]
Hi,

You propose to add a file in the form for automatically attach a file, isn't it?

That's a good idea I think, you can propose a PR if you want, because for the moment it's not on our todos ;)

**Comment by liamsorsby** [comment]
@spike31 Sorry for the late reply. Yes that is correct. I'll have a look into it when i get some free time. Just to clarify that this would be to add attachments when sending on the fly not adding attachments through the admin template. Would this still be okay to do a PR for?

**Comment by PBXg33k** [comment]
I managed to attach/embed images by extending the MessageFactory and overriding the generateMessage() method to add a simple loop and call to SwiftMailer ($message)

Replaced the following
```php
            $message = $this->createMessageInstance()
                ->setSubject($this->renderTemplate('subject', $parameters, $email->getChecksum()))
                ->setFrom($this->renderFromAddress($email, $parameters), $this->renderTemplate('from_name', $parameters, $email->getChecksum()))
                ->setTo($to)
                ->setBody($this->renderTemplate('html_content', $parameters, $email->getChecksum()), 'text/html');
```

with
```php
            $message = $this->createMessageInstance();

            // PATCH for embedding images
            $parameterKeys = array_keys($parameters);
            for($i=0;$i<count($parameters);$i++) {
                if($parameters[$parameterKeys[$i]] instanceof File) {
                    $parameters[$parameterKeys[$i]] = $message->embed(
                        \Swift_Image::fromPath(
                            $parameters[$parameterKeys[$i]]->getRealPath()
                        )
                    );
                }
            }


            $message->setSubject($this->renderTemplate('subject', $parameters, $email->getChecksum()))
                ->setFrom($this->renderFromAddress($email, $parameters), $this->renderTemplate('from_name', $parameters, $email->getChecksum()))
                ->setTo($to)
                ->setBody($this->renderTemplate('html_content', $parameters, $email->getChecksum()), 'text/html');
```

This way whenever i pass File instances to the MessageFactory it gets embedded and the variable replaced with the src string (which you can use in the template, ie showing in <img> tags)

**Comment by liamsorsby** [comment]
@PBXg33k Your method seems to assume that the array keys are numeric and run in order of 0..5. I would have used foreach instead. This would shorten the quick fix and remove any problems you would have if using non numeric parameters:

```
foreach ($parameter as $key => $param) {
    if ($param instanceof File) {
        $parameters[$key] = $message->embed(
            \Swift_Image::fromPath(
                $param->getRealPath()
            )
        );
    }
}
```

The issue that I generated above however was the need to attach the image email. You seem to be embeding into the email, which I believe if you are doing this you could just pass a variable to your twig template and render the image through twig. If you are wanting to attach the image to the email then you may need to use `->attach(Swift_Attachment::fromPath('path to image here.jpg')` rather than embed

**Comment by PBXg33k** [comment]
@liamsorsby while your code is shorter and was an approach i overlooked my code sample doesn't assume keys are numeric, $i is looking up the keys in $parametersKey which is populated by array_keys();

While i am embedding the images into the email indeed these are implictly attached to the email, i have the choice to use the variables in the template (which i do), if i don't use the variables in the mail the files still will get attached, but the references won't be printed in the rendered html output

**Comment by liamsorsby** [comment]
@PBXg33k Yes I overlooked that part. The paramKeys is an array containing the keys which will be 0 onwards.
It seems that yours is adding the file into your html to reference the image, where as I was wanting to attach a pdf to a html email hense the confusion. It looks like that maybe an additional feature that is required as well then.

**Comment by PBXg33k** [comment]
My code is intended for embedding of images indeed. I looked in the SwiftMailer code and confirmed that it doesn't matter which of the two you use, they do the exact same things. The only thing that differs is the return value :)

Where attach() only returns the ID, embed prepends the ID with 'cid:'.

```php
# swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php
/**
     * Attach a {@link Swift_Mime_MimeEntity} and return it's CID source.
     * This method should be used when embedding images or other data in a message.
     *
     * @param Swift_Mime_MimeEntity $entity
     *
     * @return string
     */
    public function embed(Swift_Mime_MimeEntity $entity)
    {
        $this->attach($entity);

        return 'cid:'.$entity->getId();
    }
```
