### ISSUE TITLE
Neither the property ... exist in "Symfony\Component\Form\FormView" in LexikMailerBundle:Email:new.html.twig 

### ISSUE THREAD

**Issue by NadaBen** [lexik/LexikMailerBundle#68]
Hello, after applying your steps , when i try to create  a new email it gives me this error:

> Neither the property "_token" nor one of the methods "_token()", "get_token()"/"is_token()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView" in LexikMailerBundle:Email:new.html.twig at line 71

**Comment by liamsorsby** [comment]
Have you disabled CSRF protection on your forms? What version of symfony are you using?
