### ISSUE TITLE
Issue with form translation

### ISSUE THREAD

**Issue by liamsorsby** [lexik/LexikMailerBundle#70]
We're developing a website in chinese with the default local being zh_CN. When We try to submit the form to submit a new layout we get the following error message. 

> String is too long , it can not be more than two characters in length

Upon looking at the error in the form submission it seems that class for chinese lang would always throw an exception. Entity/LayoutTranslation.php has validation on the protected $lang variable to ensure that the lang is always 2 characters. The problem being that the lang code for simplified chinese is zh_CH. Which then throws the validation error.

Is this something that I am doing wrong or is this a bug with the bundle not supporting the 4 character language codes?

**Comment by liamsorsby** [comment]
@cedric-g thank you. Would you be able to re-tag this for me so I can use this as a stable version rather than using master?

**Comment by cedric-g** [comment]
@liamsorsby done, v2.0.3 :)

**Comment by liamsorsby** [comment]
Thank you very much!
