### ISSUE TITLE
Invalid attribute scope

### ISSUE THREAD

**Issue by titolendable** [lexik/LexikMailerBundle#74]
I am upgrading one project from Symfony 2.8 to 3.0 and although this bundle seems to compatible, I am getting the following error:

> [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                  
>   Unable to parse file "/projects/lendable/vendor/lexik/mailer-bundle/DependencyInjection/../Resources/config/services.xml".
> 
> Element '{http://symfony.com/schema/dic/services}service', attribute 'scope': The attribute 'scope' is not allowed. 

And from what I can see in [Symfony docs](http://symfony.com/doc/2.8/cookbook/service_container/scopes.html), it has been deprecated in 2.8 and not supported in 3.0. How do I overcome this issue?

**Comment by cedric-g** [comment]
Hi, I updated the `master` branch, it should be ok now.
