### ISSUE TITLE
The service "lexik_mailer.templating" has a dependency on a non-existent parameter "twig.class".

### ISSUE THREAD

**Issue by jfdl** [lexik/LexikMailerBundle#76]
Hello,
During our migration process from Symfony 2.8.x to Symfony 3.x, while doing a cache:clear we are getting this error :

`The service "lexik_mailer.templating" has a dependency on a non-existent parameter "twig.class".`

To solve this we must add in your services.xml file at line 36 :
`<parameter key="twig.class">Twig_Environment</parameter>`

We are using "lexik/mailer-bundle": "dev-master"

Not sure what is wrong here, could you help us with this ?
Best regards

**Comment by sdieunidou** [comment]
Fixed with #78
