### ISSUE TITLE
BCC

### ISSUE THREAD

**Issue by liamsorsby** [lexik/LexikMailerBundle#81]
Is it possible to add multiple BCC addresses into the template seperated by a semicolon?

**Comment by cedric-g** [comment]
Hi, yes it should work https://github.com/lexik/LexikMailerBundle/blob/02d34ee01b4ea8a55b365e767ad63f5961ad1e66/Entity/Email.php#L397

**Comment by liamsorsby** [comment]
@cedric-g Thank you very much! I did look for the relevant code but was unable to find it.
