### ISSUE TITLE
problem in file  LexikMailerBundle/Doctrine/MetadataListener.php

### ISSUE THREAD

**Issue by ickbinhier** [lexik/LexikMailerBundle#89]
[RuntimeException]                                                                                                                                                                                              
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                                                       
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: charset in /var/www/html/vendor/lexik/mailer-bundle/Doctrine/MetadataListener.php:17               
  Stack trace:                                                                                                                                                                                                    
  #0 /var/www/html/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php(63): Lexik\Bundle\MailerBundle\Doctrine\MetadataListener->loadClassMetadata(Object(Doctrine\ORM\Event\LoadC  
  lassMetadataEventArgs))                                                                                                                                                                                         
  #1 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(242): Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('loadClassMetada...', Object(Doctrine\ORM\Event  
  \LoadClassMetadataEventArgs))                                                                                                                                                                                   
  #2 /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\C  
  lassMetadata), NULL, false, Array)                                                                                                                                                                              
  #3 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\ in /var/www/html/vendor/lexik/mailer-bundle/Doctrine/MetadataListener.php on   
  line 17

**Comment by lightglitch** [comment]
In my case this happens because I have a master/slave configuration.
